const profesorMateria = [
    {"nombreProfesor":"ADAN YAIR SANCHEZ HERNANDEZ","nombreMateria":"CONTABILIDAD","id":"22"},
    {"nombreProfesor":"ADAN YAIR SANCHEZ HERNANDEZ","nombreMateria":"ANALISIS Y TOMA DE DECISIONES","id":"106"},
    {"nombreProfesor":"ADRIAN NONATO TORRES","nombreMateria":"MATEMATICAS IV MATEMATICAS COMPUT","id":"75"},
    {"nombreProfesor":"ADRIANA YAÑEZ HERNANDEZ","nombreMateria":"PROGRAMACION I INTROD. PROG.AMBIEN","id":"21"},
    {"nombreProfesor":"AGUSTIN CESAR FRAGOSO MARTINEZ","nombreMateria":"0601 ECONOMIA","id":"97"},
    {"nombreProfesor":"AGUSTIN CESAR FRAGOSO MARTINEZ","nombreMateria":"ADMINISTRACION I PROCESO ADMVO.","id":"1"},
    {"nombreProfesor":"AIDA AGUILAR REYES","nombreMateria":"EVALUACION DE PROYECTOS","id":"101"},
    {"nombreProfesor":"AIDA AGUILAR REYES","nombreMateria":"ANALISIS Y DISEÑOS DE ALGORITMOS","id":"5"},
    {"nombreProfesor":"ALEJANDRA TORRES AGUILAR","nombreMateria":"ADMINISTRACION II ESTRUCT. ADMVAS.","id":"23"},
    {"nombreProfesor":"ALEJANDRA TORRES AGUILAR","nombreMateria":"SEMINARIO DE INVESTIGACION","id":"107"},
    {"nombreProfesor":"ALEJANDRO VALDEZ SANTAMARIA","nombreMateria":"ADMINISTRACION DE CENTROS D COMPUT","id":"77"},
    {"nombreProfesor":"ALEJANDRO ZAMARRIPA ESCOBAR","nombreMateria":"0603 DESARROLLO APLICAC. DE BASES DATOS","id":"99"},
    {"nombreProfesor":"ALEJANDRO ZAMARRIPA ESCOBAR","nombreMateria":"INFORMATICA I INTROD. A LA INFORM.","id":"3"},
    {"nombreProfesor":"ALFONSO ACEVEDO SORIANO","nombreMateria":"SEGURIDAD INFORMATICA","id":"108"},
    {"nombreProfesor":"ALFONSO ACEVEDO SORIANO","nombreMateria":"INFORMATICA II ORGAN. ARCHIV. E.DATO","id":"24"},
    {"nombreProfesor":"ALFREDO CARRILLO VERGARA","nombreMateria":"0604 REDES DE COMPUTADORAS II","id":"100"},
    {"nombreProfesor":"ALFREDO CARRILLO VERGARA","nombreMateria":"TALLER DE COMPONENTES DE HARDWARE","id":"4"},
    {"nombreProfesor":"ALFREDO VILLACORTA RAMOS","nombreMateria":"0602 INFORMATICA VI TOPICOS SELEC. INFOR","id":"98"},
    {"nombreProfesor":"ALFREDO VILLACORTA RAMOS","nombreMateria":"COMUNICACION ORAL Y ESCRITA","id":"2"},
    {"nombreProfesor":"ANDRES GUTIERREZ BARCENAS","nombreMateria":"REDES DE COMPUTADORAS I","id":"74"},
    {"nombreProfesor":"ANIBAL JOSE CAB SALINAS","nombreMateria":"PROGRAMACION III PROGRAM. VISUAL","id":"43"},
    {"nombreProfesor":"ANTONIO GAMA CAMPILLO","nombreMateria":"FINANZAS","id":"76"},
    {"nombreProfesor":"ARMANDO CARMONA BONILLA","nombreMateria":"SISTEMAS OPERATIVOS","id":"44"},
    {"nombreProfesor":"ARTEMIO SERVANDO HERNANDEZ RODRIGUEZ","nombreMateria":"INFORMATICA V INDUSTRIA SOFTWARE","id":"78"},
    {"nombreProfesor":"CARIÑO RUIZ CAMARGO","nombreMateria":"INTRODUCCION A LAS BASES DE DATOS","id":"79"},
    {"nombreProfesor":"CARLA PAMELA PEREZ SOLANO","nombreMateria":"DERECHO INFORMATICO","id":"46"},
    {"nombreProfesor":"CAROLINA BENITEZ PRESTADO","nombreMateria":"MATEMATICAS V ESTADISTICA","id":"80"},
    {"nombreProfesor":"CINTIA HERNANDEZ PEREZ","nombreMateria":"LABORATORIO DE SISTEMAS DE INFORMA","id":"109"},
    {"nombreProfesor":"CINTIA HERNANDEZ PEREZ","nombreMateria":"PROGRAMACION II PROGRAMAC.AVANZADA","id":"25"},
    {"nombreProfesor":"CLARISA CLEMENTE RODRIGUEZ","nombreMateria":"METODOLOGIA DE LA INVESTIGACION","id":"47"},
    {"nombreProfesor":"CONRADO CAMACHO ARTEAGA","nombreMateria":"MATEMATICAS III MATEMATICAS FINAN","id":"45"},
    {"nombreProfesor":"DOMINGO MARQUEZ ORTEGA","nombreMateria":"MATEMATICAS V ESTADISTICA","id":"90"},
    {"nombreProfesor":"DULCE MA. LIGIA MALO ORTEGA","nombreMateria":"MATEMATICAS I MATEMATICAS BASICAS","id":"6"},
    {"nombreProfesor":"DULCE MA. LIGIA MALO ORTEGA","nombreMateria":"0601 ECONOMIA","id":"102"},
    {"nombreProfesor":"ELIZABETH BARRERA ROMERO","nombreMateria":"PROGRAMACION III PROGRAM. VISUAL","id":"49"},
    {"nombreProfesor":"ELVIA SANCHEZ MAGADAN","nombreMateria":"INFORMATICA III ANALIS.DIS. SIST.I","id":"48"},
    {"nombreProfesor":"ELVIRA HAIDEE ORTEGA LARA","nombreMateria":"PROGRAMACION I INTROD. PROG.AMBIEN","id":"7"},
    {"nombreProfesor":"ELVIRA HAIDEE ORTEGA LARA","nombreMateria":"0602 INFORMATICA VI TOPICOS SELEC. INFOR","id":"103"},
    {"nombreProfesor":"ERENDIRA GONZALEZ COLIN","nombreMateria":"MATEMATICAS VI INVESTIGAC. OPERACIO.","id":"110"},
    {"nombreProfesor":"ERENDIRA GONZALEZ COLIN","nombreMateria":"ARQUITECTURA DE COMPUTADORAS","id":"26"},
    {"nombreProfesor":"ERNESTO HERRERA MOLINA","nombreMateria":"ADMINISTRACION I PROCESO ADMVO.","id":"8"},
    {"nombreProfesor":"ERNESTO HERRERA MOLINA","nombreMateria":"0603 DESARROLLO APLICAC. DE BASES DATOS","id":"104"},
    {"nombreProfesor":"ERWIN HUGO CRUZ HERNANDEZ","nombreMateria":"FINANZAS","id":"81"},
    {"nombreProfesor":"GABINO DIAZ DIAZ","nombreMateria":"ADMINIST.PUBLICA Y POLIT. INFORMAT.","id":"136"},
    {"nombreProfesor":"GABINO DIAZ DIAZ","nombreMateria":"EVALUACION DE PROYECTOS","id":"91"},
    {"nombreProfesor":"GABRIELA SARAHI VARGAS LOPEZ","nombreMateria":"COMUNICACION ORAL Y ESCRITA","id":"9"},
    {"nombreProfesor":"GABRIELA SARAHI VARGAS LOPEZ","nombreMateria":"0604 REDES DE COMPUTADORAS II","id":"105"},
    {"nombreProfesor":"GERARDO VIGIL SANABRIA","nombreMateria":"0601 ECONOMIA","id":"92"},
    {"nombreProfesor":"GUADALUPE BERENICE SUAREZ LOZANO","nombreMateria":"SISTEMAS OPERATIVOS","id":"50"},
    {"nombreProfesor":"GUILLERMO ACEVEDO ARCOS","nombreMateria":"MATEMATICAS II LOGICA MATEMATICA","id":"27"},
    {"nombreProfesor":"GUILLERMO ACEVEDO ARCOS","nombreMateria":"ANALISIS Y TOMA DE DECISIONES","id":"111"},
    {"nombreProfesor":"GUILLERMO MONTES GUZMAN","nombreMateria":"MATEMATICAS III MATEMATICAS FINAN","id":"51"},
    {"nombreProfesor":"HECTOR ADRIAN VEGA BECERRIL","nombreMateria":"ADMINISTRACION DE CENTROS D COMPUT","id":"82"},
    {"nombreProfesor":"HELADIO EULALIO LOPEZ MARTINEZ","nombreMateria":"INFORMATICA V INDUSTRIA SOFTWARE","id":"83"},
    {"nombreProfesor":"IRENE CORREA ESQUIVEL","nombreMateria":"INFORMATICA I INTROD. A LA INFORM.","id":"10"},
    {"nombreProfesor":"IVAN NUÑEZ CONSUELOS","nombreMateria":"DERECHO INFORMATICO","id":"52"},
    {"nombreProfesor":"JAIME NAVARRO MEJIA","nombreMateria":"MATEMATICAS VI INVESTIGAC. OPERACIO.","id":"120"},
    {"nombreProfesor":"JAIME NAVARRO MEJIA","nombreMateria":"INFORMATICA II ORGAN. ARCHIV. E.DATO","id":"36"},
    {"nombreProfesor":"JAVIER GARCIA","nombreMateria":"PROGRAMACION III PROGRAM. VISUAL","id":"55"},
    {"nombreProfesor":"JOSE ALBERTO GOMEZ ESCOJIDO","nombreMateria":"SISTEMAS OPERATIVOS","id":"56"},
    {"nombreProfesor":"JOSE ANTONIO HERNANDEZ SORIANO","nombreMateria":"INTRODUCCION A LAS BASES DE DATOS","id":"84"},
    {"nombreProfesor":"JOSE CRUZ GERVACIO","nombreMateria":"ANALISIS Y DISEÑOS DE ALGORITMOS","id":"12"},
    {"nombreProfesor":"JOSÉ FRANCISCO COVARRUBIAS GARCIA","nombreMateria":"MATEMATICAS I MATEMATICAS BASICAS","id":"13"},
    {"nombreProfesor":"JOSE JUAN RICO CASTRO","nombreMateria":"METODOLOGIA DE LA INVESTIGACION","id":"53"},
    {"nombreProfesor":"JOSE LUIS TORRES REYES","nombreMateria":"FINANZAS","id":"86"},
    {"nombreProfesor":"JOSÉ MANUEL CASTAÑEDA RAMIREZ","nombreMateria":"CONTABILIDAD DE COSTOS","id":"58"},
    {"nombreProfesor":"JOSE MANUEL HERRERA ARELLANO","nombreMateria":"SEGURIDAD INFORMATICA","id":"113"},
    {"nombreProfesor":"JOSE MANUEL HERRERA ARELLANO","nombreMateria":"ADMINISTRACION II ESTRUCT. ADMVAS.","id":"29"},
    {"nombreProfesor":"JUAN ANGEL FLORES RIVERA","nombreMateria":"TALLER DE COMPONENTES DE HARDWARE","id":"11"},
    {"nombreProfesor":"JUAN ARMANDO RESENDIZ PONCE","nombreMateria":"INFORMATICA III ANALIS.DIS. SIST.I","id":"54"},
    {"nombreProfesor":"JUAN CARLOS CORREA URIBE ","nombreMateria":"LABORATORIO DE SISTEMAS DE INFORMA","id":"119"},
    {"nombreProfesor":"JUAN CARLOS CORREA URIBE ","nombreMateria":"ADMINISTRACION II ESTRUCT. ADMVAS.","id":"35"},
    {"nombreProfesor":"JUAN MIGUEL MARTINEZ MALDONADO","nombreMateria":"MATEMATICAS III MATEMATICAS FINAN","id":"57"},
    {"nombreProfesor":"JUAN SILVA HERNANDEZ","nombreMateria":"LABORATORIO DE SISTEMAS DE INFORMA","id":"114"},
    {"nombreProfesor":"JUAN SILVA HERNANDEZ","nombreMateria":"INFORMATICA II ORGAN. ARCHIV. E.DATO","id":"30"},
    {"nombreProfesor":"JUDITH MAYTE FLORES PEREZ","nombreMateria":"0602 INFORMATICA VI TOPICOS SELEC. INFOR","id":"93"},
    {"nombreProfesor":"JULIO CESAR GUTIERREZ PELAEZ","nombreMateria":"SEMINARIO DE INVESTIGACION","id":"112"},
    {"nombreProfesor":"JULIO CESAR GUTIERREZ PELAEZ","nombreMateria":"CONTABILIDAD","id":"28"},
    {"nombreProfesor":"JULIO CESAR RAMON MALDONADO RODRIGUEZ","nombreMateria":"0603 DESARROLLO APLICAC. DE BASES DATOS","id":"94"},
    {"nombreProfesor":"JULIO MOISES SANCHEZ BARRERA","nombreMateria":"MATEMATICAS V ESTADISTICA","id":"85"},
    {"nombreProfesor":"KARINA SIMON FARFAN","nombreMateria":"MERCADOTECNIA","id":"59"},
    {"nombreProfesor":"LEON MAURICIO MUÑOZ MIRANDA","nombreMateria":"PROGRAMACION IV PROGRAM.INTERFACES","id":"61"},
    {"nombreProfesor":"LEONEL GUALBERTO LOPEZ SALAZAR","nombreMateria":"INFORMATICA IV ANALIS. DIS. SIST. II","id":"60"},
    {"nombreProfesor":"LIANA LOPEZ PACHECO","nombreMateria":"0604 REDES DE COMPUTADORAS II","id":"95"},
    {"nombreProfesor":"LUCIA ESTRADA CHAVEZ","nombreMateria":"PROGRAMACION I INTROD. PROG.AMBIEN","id":"14"},
    {"nombreProfesor":"MANUEL JAUREGUI RENAULT","nombreMateria":"MATEMATICAS IV MATEMATICAS COMPUT","id":"63"},
    {"nombreProfesor":"MARCELA LUCINA MENESES JIMENEZ","nombreMateria":"ARQUITECTURA DE COMPUTADORAS","id":"32"},
    {"nombreProfesor":"MARCELA LUCINA MENESES JIMENEZ","nombreMateria":"ANALISIS Y TOMA DE DECISIONES","id":"116"},
    {"nombreProfesor":"MARCO ANTONIO CRUZ MENDOZA","nombreMateria":"PROGRAMACION IV PROGRAM.INTERFACES","id":"67"},
    {"nombreProfesor":"MARGARITA FLORES ZEPEDA","nombreMateria":"ADMINISTRACION I PROCESO ADMVO.","id":"15"},
    {"nombreProfesor":"MARIA ARACELI NIVON ZAGHI","nombreMateria":"MERCADOTECNIA","id":"65"},
    {"nombreProfesor":"MARIA GUADALUPE VAZQUEZ SALAZAR","nombreMateria":"REDES DE COMPUTADORAS I","id":"62"},
    {"nombreProfesor":"MARICELA LARA MARTINEZ","nombreMateria":"INFORMATICA IV ANALIS. DIS. SIST. II","id":"66"},
    {"nombreProfesor":"MARISELA ABUNDIS ESCALANTE","nombreMateria":"COMUNICACION ORAL Y ESCRITA","id":"16"},
    {"nombreProfesor":"MARTIN MONTIEL BADILLO","nombreMateria":"MATEMATICAS VI INVESTIGAC. OPERACIO.","id":"115"},
    {"nombreProfesor":"MARTIN MONTIEL BADILLO","nombreMateria":"PROGRAMACION II PROGRAMAC.AVANZADA","id":"31"},
    {"nombreProfesor":"MAURICIO ARIAS VELAZQUEZ","nombreMateria":"REDES DE COMPUTADORAS I","id":"68"},
    {"nombreProfesor":"MAURICIO JAQUES SOTO","nombreMateria":"CONTABILIDAD DE COSTOS","id":"64"},
    {"nombreProfesor":"MIGUEL ANGEL MORENO","nombreMateria":"PROGRAMACION II PROGRAMAC.AVANZADA","id":"37"},
    {"nombreProfesor":"MIGUEL ANGEL ROJAS GONZALEZ","nombreMateria":"ARQUITECTURA DE COMPUTADORAS","id":"38"},
    {"nombreProfesor":"MIRIAM TALIA LOPEZ DIAZ","nombreMateria":"MATEMATICAS II LOGICA MATEMATICA","id":"39"},
    {"nombreProfesor":"NAHUM LOPEZ GOMEZ","nombreMateria":"INFORMATICA I INTROD. A LA INFORM.","id":"17"},
    {"nombreProfesor":"OFELIA ESPERANZA ARROYO FAL","nombreMateria":"ADMINISTRACION DE CENTROS D COMPUT","id":"87"},
    {"nombreProfesor":"OLGA LUCIA CABRERA TEJADA","nombreMateria":"TALLER DE COMPONENTES DE HARDWARE","id":"18"},
    {"nombreProfesor":"OMAR CISNEROS BELTRAN","nombreMateria":"ANALISIS Y DISEÑOS DE ALGORITMOS","id":"19"},
    {"nombreProfesor":"OMAR GADDIEL PEREZ ALVARADO","nombreMateria":"SEMINARIO DE INVESTIGACION","id":"117"},
    {"nombreProfesor":"OMAR GADDIEL PEREZ ALVARADO","nombreMateria":"MATEMATICAS II LOGICA MATEMATICA","id":"33"},
    {"nombreProfesor":"OMAR NIETO NIETO","nombreMateria":"SEGURIDAD INFORMATICA","id":"118"},
    {"nombreProfesor":"OMAR NIETO NIETO","nombreMateria":"CONTABILIDAD","id":"34"},
    {"nombreProfesor":"OSCAR HERNANDEZ SANCHEZ","nombreMateria":"EVALUACION DE PROYECTOS","id":"96"},
    {"nombreProfesor":"OSCAR VILCHIS GUERRA","nombreMateria":"MATEMATICAS IV MATEMATICAS COMPUT","id":"69"},
    {"nombreProfesor":"REYNA ARRIAGA DIAZ","nombreMateria":"AUDITORIA EN INFORMATICA","id":"121"},
    {"nombreProfesor":"REYNA ARRIAGA DIAZ","nombreMateria":"DERECHO INFORMATICO","id":"40"},
    {"nombreProfesor":"ROCIO GONZALEZ HERNANDEZ","nombreMateria":"CONTABILIDAD DE COSTOS","id":"70"},
    {"nombreProfesor":"ROSALBA NANCY ROSAS FONSECA","nombreMateria":"MERCADOTECNIA","id":"71"},
    {"nombreProfesor":"SALVADOR JOSE DEL CASTILLO SCHMIDHUBER","nombreMateria":"MATEMATICAS I MATEMATICAS BASICAS","id":"20"},
    {"nombreProfesor":"SOFIA FUENTES GUTIERREZ","nombreMateria":"INFORMATICA IV ANALIS. DIS. SIST. II","id":"72"},
    {"nombreProfesor":"VALENTIN ROLDAN VAZQUEZ","nombreMateria":"PROGRAMACION IV PROGRAM.INTERFACES","id":"73"},
    {"nombreProfesor":"VICENTE VAZQUEZ SUAREZ","nombreMateria":"INTRODUCCION A LAS BASES DE DATOS","id":"89"},
    {"nombreProfesor":"VICTOR ENRIQUE GONZALEZ VARGAS","nombreMateria":"ETICA Y DESARROLLO PROFESIONAL","id":"122"},
    {"nombreProfesor":"VICTOR ENRIQUE GONZALEZ VARGAS","nombreMateria":"METODOLOGIA DE LA INVESTIGACION","id":"41"},
    {"nombreProfesor":"VLADISLAV KHARTCHENKO","nombreMateria":"INFORMATICA V INDUSTRIA SOFTWARE","id":"88"},
    {"nombreProfesor":"XOCHITL MUÑOZ GARCIA","nombreMateria":"INFORMATICA III ANALIS.DIS. SIST.I","id":"42"}
    ];

    export default profesorMateria;