const arregloFalsoMaterias=[
    {
      "folioAsig": 30820211,
      "IDpm": 1,
      "IDhorario": 11111,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 100,
      "Nombre": "ADMINISTRACION I PROCESO ADMVO.",
      "Semestre": 1,
      "Creditos": 6,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Lunes",
      "Horario": "7:00-8:30",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820212,
      "IDpm": 2,
      "IDhorario": 11211,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 101,
      "Nombre": "COMUNICACION ORAL Y ESCRITA",
      "Semestre": 1,
      "Creditos": 6,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Lunes",
      "Horario": "8:30-10:00",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820213,
      "IDpm": 3,
      "IDhorario": 11311,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 102,
      "Nombre": "INFORMATICA I INTROD. A LA INFORM.",
      "Semestre": 1,
      "Creditos": 12,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Lunes",
      "Horario": "10:00-12:30",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820214,
      "IDpm": 4,
      "IDhorario": 11411,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 104,
      "Nombre": "TALLER DE COMPONENTES DE HARDWARE",
      "Semestre": 1,
      "Creditos": 3,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Lunes",
      "Horario": "12:30-14:00",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820215,
      "IDpm": 5,
      "IDhorario": 11511,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 105,
      "Nombre": "ANALISIS Y DISEÑOS DE ALGORITMOS",
      "Semestre": 1,
      "Creditos": 8,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Martes",
      "Horario": "8:00-10:00",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820216,
      "IDpm": 6,
      "IDhorario": 11611,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 106,
      "Nombre": "MATEMATICAS I MATEMATICAS BASICAS",
      "Semestre": 1,
      "Creditos": 8,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Martes",
      "Horario": "10:00-12:30",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820220,
      "IDpm": 10,
      "IDhorario": 11211,
      "Cupo": 45,
      "Inscritos": 0,
      "Grupo": "1102",
      "IDmateria": 106,
      "Nombre": "MATEMATICAS I MATEMATICAS BASICAS",
      "Semestre": 1,
      "Creditos": 8,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Lunes",
      "Horario": "8:30-10:00",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820217,
      "IDpm": 7,
      "IDhorario": 11711,
      "Cupo": 30,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 107,
      "Nombre": "PROGRAMACION I INTROD. PROG.AMBIEN",
      "Semestre": 1,
      "Creditos": 8,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Martes",
      "Horario": "12:30-14:00",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
      "folioAsig": 30820218,
      "IDpm": 8,
      "IDhorario": 11211,
      "Cupo": 35,
      "Inscritos": 0,
      "Grupo": "1101",
      "IDmateria": 203,
      "Nombre": "PROGRAMACION II PROGRAMAC.AVANZADA",
      "Semestre": 2,
      "Creditos": 8,
      "Tipo": "OBL",
      "PlanEstudios": "1119",
      "Dia": "Lunes",
      "Horario": "8:30-10:00",
      "Turno": "Matutino",
      "SemestreA": "2"
    },
    {
        "folioAsig": 30820211,
        "IDpm": 1,
        "IDhorario": 11111,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 100,
        "Nombre": "ADMINISTRACION I PROCESO ADMVO.",
        "Semestre": 1,
        "Creditos": 6,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Lunes",
        "Horario": "7:00-8:30",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820212,
        "IDpm": 2,
        "IDhorario": 11211,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 101,
        "Nombre": "COMUNICACION ORAL Y ESCRITA",
        "Semestre": 1,
        "Creditos": 6,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Lunes",
        "Horario": "8:00-10:00",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820213,
        "IDpm": 3,
        "IDhorario": 11311,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 102,
        "Nombre": "INFORMATICA I INTROD. A LA INFORM.",
        "Semestre": 1,
        "Creditos": 12,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Lunes",
        "Horario": "7:00-8:20",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820214,
        "IDpm": 4,
        "IDhorario": 11411,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 104,
        "Nombre": "TALLER DE COMPONENTES DE HARDWARE",
        "Semestre": 1,
        "Creditos": 3,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Lunes",
        "Horario": "12:30-14:00",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820215,
        "IDpm": 5,
        "IDhorario": 11511,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 105,
        "Nombre": "ANALISIS Y DISEÑOS DE ALGORITMOS",
        "Semestre": 1,
        "Creditos": 8,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Martes",
        "Horario": "8:00-10:00",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820216,
        "IDpm": 6,
        "IDhorario": 11611,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1103",
        "IDmateria": 106,
        "Nombre": "MATEMATICAS I MATEMATICAS BASICAS",
        "Semestre": 1,
        "Creditos": 8,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Martes",
        "Horario": "10:00-12:30",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820220,
        "IDpm": 10,
        "IDhorario": 11211,
        "Cupo": 45,
        "Inscritos": 0,
        "Grupo": "1104",
        "IDmateria": 106,
        "Nombre": "MATEMATICAS I MATEMATICAS BASICAS",
        "Semestre": 1,
        "Creditos": 8,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Lunes",
        "Horario": "8:30-10:00",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820217,
        "IDpm": 7,
        "IDhorario": 11711,
        "Cupo": 30,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 107,
        "Nombre": "PROGRAMACION I INTROD. PROG.AMBIEN",
        "Semestre": 1,
        "Creditos": 8,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Martes",
        "Horario": "12:30-14:00",
        "Turno": "Matutino",
        "SemestreA": "2"
      },
      {
        "folioAsig": 30820218,
        "IDpm": 8,
        "IDhorario": 11211,
        "Cupo": 35,
        "Inscritos": 0,
        "Grupo": "1102",
        "IDmateria": 203,
        "Nombre": "PROGRAMACION II PROGRAMAC.AVANZADA",
        "Semestre": 2,
        "Creditos": 8,
        "Tipo": "OBL",
        "PlanEstudios": "1119",
        "Dia": "Lunes",
        "Horario": "8:30-10:00",
        "Turno": "Matutino",
        "SemestreA": "2"
      }
  ]

  export default arregloFalsoMaterias;