INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(116,"INGENIERIA MECANICA ELECTRICA",1,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(126,"TECNOLOGIA",1,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(130,"INGENIERIA EN TELECOMUNICACIONES, SISTEMAS Y ELECTRONICA",1,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(204,"INGENIERIA AGRICOLA",2,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(207,"MEDICINA VETERINARIA Y ZOOTECNIA",2,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(301,"ADMINISTRACION",3,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(304,"CONTADURIA",3,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(308,"INFORMATICA",3,119);
INSERT INTO carrera(IDcarrera,Nombre,Area,IDplantel)VALUES(423,"DISEÑO Y COMUNICACION VISUAL",4,119);
