INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0100,"ADMINISTRACION I PROCESO ADMVO.",1,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0101,"COMUNICACION ORAL Y ESCRITA",1,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0102,"INFORMATICA I INTROD. A LA INFORM.",1,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0104,"TALLER DE COMPONENTES DE HARDWARE",1,3,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0105,"ANALISIS Y DISEÑOS DE ALGORITMOS",1,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0106,"MATEMATICAS I MATEMATICAS BASICAS",1,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0107,"PROGRAMACION I INTROD. PROG.AMBIEN",1,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0200,"CONTABILIDAD",2,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0201,"ADMINISTRACION II ESTRUCT. ADMVAS.",2,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0202,"INFORMATICA II ORGAN. ARCHIV. E.DATO",2,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0203,"PROGRAMACION II PROGRAMAC.AVANZADA",2,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0204,"ARQUITECTURA DE COMPUTADORAS",2,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0205,"MATEMATICAS II LOGICA MATEMATICA",2,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0300,"DERECHO INFORMATICO",3,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0301,"METODOLOGIA DE LA INVESTIGACION",3,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0302,"INFORMATICA III ANALIS.DIS. SIST.I",3,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0303,"PROGRAMACION III PROGRAM. VISUAL",3,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0304,"SISTEMAS OPERATIVOS",3,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0305,"MATEMATICAS III MATEMATICAS FINAN",3,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0400,"CONTABILIDAD DE COSTOS",4,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0401,"MERCADOTECNIA",4,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0402,"INFORMATICA IV ANALIS. DIS. SIST. II",4,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0403,"PROGRAMACION IV PROGRAM.INTERFACES",4,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0404,"REDES DE COMPUTADORAS I",4,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0405,"MATEMATICAS IV MATEMATICAS COMPUT",4,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0500,"FINANZAS",5,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0501,"ADMINISTRACION DE CENTROS D COMPUT",5,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0502,"INFORMATICA V INDUSTRIA SOFTWARE",5,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0503,"INTRODUCCION A LAS BASES DE DATOS",5,10,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0504,"MATEMATICAS V ESTADISTICA",5,10,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0600,"EVALUACION DE PROYECTOS",6,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0601,"0601 ECONOMIA",6,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0602,"0602 INFORMATICA VI TOPICOS SELEC. INFOR",6,12,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0603,"0603 DESARROLLO APLICAC. DE BASES DATOS",6,10,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0604,"0604 REDES DE COMPUTADORAS II",6,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0700,"ANALISIS Y TOMA DE DECISIONES",7,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0701,"SEMINARIO DE INVESTIGACION",7,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0702,"SEGURIDAD INFORMATICA",7,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0703,"LABORATORIO DE SISTEMAS DE INFORMA",7,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0704,"MATEMATICAS VI INVESTIGAC. OPERACIO.",7,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0800,"AUDITORIA EN INFORMATICA",8,8,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0801,"ETICA Y DESARROLLO PROFESIONAL",8,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0900,"ADMINIST.PUBLICA Y POLIT. INFORMAT.",9,6,"OBL","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0023,"INTROD. AL DERECHO Y DERECHO CIVIL",0,9,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0024,"CONTABILIDAD SUPERIOR",0,12,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0025,"COMUNICACIONES",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0026,"TEORIA DE LAS ORGANIZACIONES",0,9,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0027,"DERECHO DEL TRABAJO",0,9,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0028,"CONTAB. DE ORGS. MERCANTILES",0,9,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0029,"PRINCIPIOS Y SISTEMAS DE PRODUCC.",0,12,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0030,"APLIC. CONTAB. DE LOS IMPUESTOS",0,9,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0031,"AUDITORIA BASICA",0,12,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0032,"INVESTIGACION DE MERCADOS I",0,12,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0033,"PROBLEMAS DE MEXICO",0,9,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0034,"PLAN Y CONTROL DE LA PRODUCCION",0,12,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0146,"ADMINISTRAC. INTERNACIONAL COMPAR.",0,6,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0147,"ANALIS.FINANC.MAT.SISTEM.ELECTRON.",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0148,"ANALISIS MATEM.APLIC. A LA ADMINIST",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0149,"COMERCIO EXTERIOR I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0158,"CONTABILIDADES ESPECIALES",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0159,"HABILIDADES DE LIDERAZGO ESTRATEG.",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0160,"HERRAMIENTAS DE COMPUTO AVANZADO",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0161,"INGLES I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0162,"INGLES II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0163,"INTELIGENCIA DE NEGOCIOS",0,6,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0164,"SEMINARIO DE TITULACION",0,0,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0165,"SIMULACION DE NEGOCIOS",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0166,"SISTEMAS INFORMAT.APLICAD.PRODUCC.",0,6,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0001,"SEM. DE MULTIMEDIA I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0002,"SEM. DE PROCESO DISTRIBUIDO I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0003,"SEM. DE SISTEMAS EXPERTOS I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0004,"SEM. DE GRAFICACION POR COMPUT. I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0005,"SEM. DE SISTEMAS OPERAT. REDES I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0006,"SEM. DE COMERCIO ELECTRONICO I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0007,"SEM. DE NORMAS Y ESTANDARES I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0008,"SEM. DE ADMON. RECURS. HUMS.INFOR.I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0009,"SEM. DE PROGRAMACION INTERNET I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0010,"SEM. DE INTELIGENCIA ARTIFICIAL I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0011,"SEM. DE REDES DE COMPUTADORAS I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0012,"SEM. DE MULTIMEDIA II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0013," SEM. DE PROCESO DISTRIBUIDO II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0015,"SEM. DE GRAFICACION POR COMPUT. II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0016,"SEM. DE SISTEMAS OPERAT. REDES II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0017,"SEM. DE COMERCIO ELECTRONICO II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0018,"SEM. DE NORMAS Y ESTANDARES II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0019,"SEM. DE ADMON.RECURS.HUMS.INFOR II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0020,"SEM. DE PROGRAMACION INTERNET II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0021,"SEM. DE INTELIGENCIA ARTIFICIAL II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0022,"SEM. DE REDES DE COMPUTADORAS II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0035," SEM. DE SISTEMAS EXPERTOS II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0061,"EM.DESARROLLO APLICACIONES WEB I",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0062,"SEM.DESARROLLO APLICACIONES WEB II",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0063,"SEM.DE ADMON.DE SERVICIOS DE TI",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0064,"SEM.DE ANALIS.EXTRAC.CONOC.BASE DA",0,8,"OPT","1119");
INSERT INTO materia(IDmateria,Nombre,Semestre,Creditos,Tipo,PlanEstudios)VALUES(0065,"SEM.DE BASES DE DATOS AVANZADAS",0,8,"OPT","1119");
